### PR TITLE
Add verbose mode

### PR DESCRIPTION
**Pull request by ljos**
* hunpos/tagger.ml (main): Add a quiet setting to command line that
removes the reporting from the tagger.

### CODE REVIEW

**Comment by giuliopaci** [comment]
I completely second this change. I usually prefer the opposite behavior (i.e., quiet by default, verbose on request). If you agree with this, would you mind to implement this feature adding a "verbose" flag instead of a "quiet" flag?

**Comment by ljos** [comment]
Yes, I also like it that way. I was just being conservative in keeping the old behaviour. I will change it.

**Comment by ljos** [comment]
Changed.

**Comment by giuliopaci** [comment]
I committed a small fix for this. :-)

**Comment by ljos** [comment]
Yes, I was a bit quick. Sorry for that.

**Pull request merged**
